### ISSUE TITLE
Portfolio Details - Job Image Reel Arrows - Arrows have disappeared on Institutional and Recreational details pages. Please see screenshot

### ISSUE THREAD

**Issue by tgascoigne14** [CCI-Studios/Wellington-Builders-2015#26]

**Comment by hemantcci** [comment]
If possible can you send me screenshot and try refreshing the page. I am not able to see this issue.

**Comment by tgascoigne14** [comment]
![screen shot 2016-04-11 at 10 47 53 am](https://cloud.githubusercontent.com/assets/8631079/14431307/1167c1ec-ffd3-11e5-8b9b-5199c8d5b38d.png)

**Comment by hemantcci** [comment]
Actually If projects are less than 5 or 5 it doesn't show arrows because there is nothing to scroll.
