### ISSUE TITLE
Responsive - Contact page - Can we please switch the location of the form and contact info to look like the design?

### ISSUE THREAD

**Issue by tgascoigne14** [CCI-Studios/Wellington-Builders-2015#4]

**Comment by hemantcci** [comment]
Can we keep it the way it is right now because info comes after the form in page. so it is autmatically falls down in responsive.

**Comment by tgascoigne14** [comment]
No problem! We can keep it I just wanted to double check.

_Tina Gascoigne_
_Account Lead_
CCI Studios, Inc.
_Mail:_ 136 Christina St. N., Sarnia, ON N7T 5T9
_Phone:_ (519) 337-8837
_Fax:_ (519) 337-8316
_Email:_ tgascoigne@ccistudios.com
_Web:_ www.ccistudios.com

**2010, 2012 & 2013 Outstanding Business Achievement Award Recipient**

P _Please print this e-mail only if necessary_

 _You have received this email because you have a business relationship
with CCI Studios.  If you believe this was done in error or if you would
like to unsubscribe from any future digital communication, please click
here http://www.ccistudios.com/unsubscribe._
